var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                      *                         ",
   "                                                     xxx            xxx         ",
   "                                                    >       x                   ",
   "                                    o o                      x                  ",
   "                                                xxx                             ",
   "                                 @   *                                          ",
   "                              xxxxxxx                                       xx  ",
   "                                          o o                                x  ",
   "                       o                                                     x  ",
   "  x                            v         xxxxx                             o x  ",
   "  x         xxxx       o                                                 xxxxx  ",
   "  x o                                               xxxxxxx                     ",
   "  xxxxxx           xxxxxxx                                                      ",
   "   x!!!!!!!!!!!!!x                                              xxxxxx          ",
   "   xxxxxxxxxxxxxxx     !!!!!!!!!!!!!!!!!!!!!!!!!!!                              ",
   "                       xxxxx                  xxxx                              ",
   "                                                                                ",
   "                                                                                "],
  ["       x                                                                                     ",
   "       x                                                                                     ",
   "       x                                                                                     ",
   "       x                                                                                     ",
   "       x              v                                                                      ",
   "       x                                                      xxx           xxx              ",
   "       x   o                                o                x                 x             ",
   "       x   o                                      x         x         o         x            ",
   "       xxxxxxxxxxxx                 v            x           xx               xx             ",
   "                      xxxxx                     x              xx!!!  x  !!!!xx              ",
   "                        x                      x                 xx!!!!!!!xx                 ",
   "                       x    o                 x                    xx!!!xx                   ",
   "                       xxxxxx                 x                      xxx                     ",
   "                        x                      x                                             ",
   "                         x                 o    x         xxxxxxxxxxxxxxxxxxxxxxxxx          ",
   "                          x               xxxxxxxx        x                    *  x          ",
   "                           x                      x       x                     > x          ",
   "                            xxxxxx                 x                                         ",
   "                                                                           xxxxxx            ",
   "                                       xxxxx                      xxxxxxxxx                  ",
   "        @                                                                                    ",
   "      xxxxx                                      xxxxxxxxxx                                  ",
   "     xx   xx                   xxxxxxxx                                                      ",
   "    x       x                                                                                ",
   "   xx         xx        xxx                                                                  ",
   "  x              x!!!!!!x                                                                    ",
   " xx                xxxxx                                                                     ",
   "x                                                                                            ",
   "                                                                                             ",
   "                                                                                             "],
  ["                        xx        xx                                                                           ",
   "                     x     x   x     x                                                                         ",
   "                    x        x        x                                                                        ",
   "                    x                 x                                                                        ",
   "                     x               x                                                                         ",
   "                       x           x                                                                           ",
   "                         x       x                                                                             ",
   "                       xxxxxxxxxxxxxxx                                                                         ",
   "                     xxxxxxxxxxxxxxxxxxx                                                                       ",
   "                   xxxxxxxxxxxxxxxxxxxxxxx                 xxx                                                 ",
   "                x                          x             x     x                                               ",
   "             x                                x         x       x                                              ",
   "          x                                      x     x        x                                              ",
   "        x                                          x   x       x                                               ",
   "      x                                              x        x                                                ",
   "     x                                                x     x                                                  ",
   "    x                   xxxxxxxxxxxxxxx                x      x                                                ",
   "   x    o                                               x       x                                              ",
   "   x              v                                  *  x         x                                            ",
   "   xxxxxxxxxxxxx                               xxxxxxxxxx   x      x                                           ",
   "   x                                                    x    x     x                                           ",
   "   x                                   xxxxxx           x      xxx   x                                         ",
   "   x                                   x                x            x  o                                      ",
   "   x                             xxxxxx                 x              x                                       ",
   "   x                             x                      x                x                                     ",
   "   x                        xxxx                      x                  xx                                  ",
   "   x                                                    x                                                      ",
   "   x                                                                                                           ",
   "   x                                                                              xxxx               xxxx      ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                              xx           xx          ",
   "   x   *            >               o                                                    xx      xx            ",
   "   x                                          xxxxxx                                        xxxxx              ",
   "   x                                                                                   xxxxxxxxxxxxxxxx        ",
   "   x   @                                                                                                       ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                  xxxxx              ",
   "                                                                                                               ",
   "                                                                                                            "
 ],
 ["                                                                                         ",
  "                                                                                         ",
  "                                                                                         ",
  "                                                                                         ",
  "                                                                                         ",
  "                                                                                         ",
  "                                                                                         ",
  "                                                                                         ",
  "                                                                                         ",
  "        x          x               x            x         xxxx           xxx             ",
  "        x          x               x            x       x      x       x     x           ",
  "        x          x               x            x      x        x    x         x         ",
  "        x          x               x      x     x      x        x    x         x         ",
  "         x        x                 x    x x    x       x      x     x         x         ",
  "           xxxxxx                    xxxx   xxxx          xxxx       x         x         ",
  "                                                                                         ",
  "                                                                                         ",
  "                                                                                         ",
  "                                                                                         ",
  "                                                                                         ",
  "                                                                                         ",
  "                                                                                         ",
  "               @                                                                         ",
  "         xxxxxxxxxx  xxxxxxxxxxxx  xxxxxxxxxx   xxxxxxxxxx xxxxxxxxxxxxxx xxxxxxx        ",
  "                                                                                         ",
 ],
 ];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
