var GAMExLEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                      *                          ",
   "                                                     xxx            xxx           ",
   "                                                    >       x                   ",
   "                                    o o                      x                  ",
   "                                                xxx                                ",
   "                                 @   *                                           ",
   "                              xxxxxxx                                       xx  ",
   "                                          o o                                x  ",
   "                       o                                                     x  ",
   "  x                            v         xxxxx                             o x  ",
   "  x         xxxx       o                                                 xxxxx  ",
   "  x o                                               xxxxxxx                     ",
   "  xxxxxx           xxxxxxx                                                      ",
   "   x!!!!!!!!!!!!!x                                              xxxxxx          ",
   "   xxxxxxxxxxxxxxx     !!!!!!!!!!!!!!!!!!!!!!!!!!!                              ",
   "                       xxxxx                  xxxx                              ",
   "                                                                                ",
   "                                                                                "],
  ["       x                                                                                     ",
   "       x                                                                                     ",
   "       x                                                                                     ",
   "       x                                                                                     ",
   "       x              v                                                                      ",
   "       x                                                      xxx           xxx              ",
   "       x   o                                o                x                 x             ",
   "       x   o                                      x         x         o         x            ",
   "       xxxxxxxxxxxx                 v            x           xx               xx             ",
   "                      xxxxx                     x              xx!!!  x  !!!!xx              ",
   "                        x                      x                 xx!!!!!!!xx                 ",
   "                       x    o                 x                    xx!!!xx                   ",
   "                       xxxxxx                 x                      xxx                     ",
   "                        x                      x                                             ",
   "                         x                 o    x         xxxxxxxxxxxxxxxxxxxxxxxxx          ",
   "                          x               xxxxxxxx        x                    *  x          ",
   "                           x                      x       x                     > x          ",
   "                            xxxxxx                 x                                         ",
   "                                                                           xxxxxx            ",
   "                                       xxxxx                      xxxxxxxxx                  ",
   "        @                                                                                    ",
   "      xxxxx                                      xxxxxxxxxx                                  ",
   "     xx   xx                   xxxxxxxx                                                      ",
   "    x       x                                                                                ",
   "   xx         xx        xxx                                                                  ",
   "  x              x!!!!!!x                                                                    ",
   " xx                xxxxx                                                                     ",
   "x                                                                                            ",
   "                                                                                             ",
   "                                                                                             "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                       xxxxxxxxxxxxxxx                                                                        ",
   "                     xxxxxxxxxxxxxxxxxxx                                                                      ",
   "                   xxxxxxxxxxxxxxxxxxxxxxx                                                                    ",
   "                x                          x                                                                  ",
   "             x                                x                                                               ",
   "          x                                      x                                                            ",
   "        x                                          x                                                          ",
   "      x                                              x                                                        ",
   "     x                                                x                                                       ",
   "    x                   xxxxxxxxxxxxxxx                x                                                      ",
   "   x    o                                               x                                                     ",
   "   x              v                                  *   x                                                    ",
   "   xxxxxxxxxxxxx                               xxxxxxxxxx                                                     ",
   "   x                                                    x                                                     ",
   "   x                                   xxxxxx           x                                                     ",
   "   x                                   x                x                                                     ",
   "   x                             xxxxxx                 x                                                     ",
   "   x                             x                      x                                                     ",
   "   x                          xxxxxx                    x                                                     ",
   "   x                  xxx!!!!!x                         x                                                     ",
   "   x       xxxxxx                                                                                             ",
   "   x                                                                                                          ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                    ",
   "   x                >               o                                                                         ",
   "   x                                         xxxxxxx                                                          ",
   "   x     @                                                                                                    ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                    ",
   "                                                                                                              "],
  ["                                   xxx x       ",
   "                                       x       ",
   "                                   xxxxx       ",
   "                                   x           ",
   "                                   x xxx       ",
   "                          o                    ",
   "         xxxx  xxx                             ",
   "    xxxxxx        x xxxx                       ",
   " xxxx    x    x    x    xxxx                   ",
   " x    xx   x   x   x   xx    x                 ",
   " xx    xx  x  x  x  xx    xx                   ",
   "  xxx xxxx  xxxxxxxxxxx  xxxx xxx              ",
   "   x       xx xxxxxxxxx xx       x             ",
   "  xxxxxx xxxxxxxxxxx xxxxxx                    ",
   "  x      xxx xxxxxxxxx xxx      x              ",
   "  xxxxxxx   xxxxxxxxxxx   xxxxxxx              ",
   " x    xx  x  x  x  xx    x                     ",
   " xxxxxx   x   x   x   xxxxxx                   ",
   "    x   x    x    x    x                       ",
   "  xxxxx   x x   xxxxxx                         ",
   "          xxx   xxx                            ",
   "                                               ",
 ],
 ];

if (typeof module != "undefined" && modulexexports)
  modulexexports = GAMExLEVELS;
